    <script src="{{asset('vendor/global/global.min.js')}}"></script>
	<script src="{{asset('vendor/chart.js/Chart.bundle.min.js')}}"></script>
	<script src="{{asset('vendor/jquery-nice-select/js/jquery.nice-select.min.js')}}"></script>
	<script src="{{asset('vendor/apexchart/apexchart.js')}}"></script>
	<script src="{{asset('vendor/chart.js/Chart.bundle.min.js')}}"></script>
    <script src="{{asset('vendor/peity/jquery.peity.min.js')}}"></script>
	<script src="{{asset('js/plugins-init/piety-init.js') }}"></script>
	<script src="{{asset('js/dashboard/dashboard-1.js')}}"></script>
	<script src="{{asset('vendor/owl-carousel/owl.carousel.js')}}"></script>
    <script src="{{asset('js/custom.min.js')}}"></script>
	<script src="{{asset('js/dlabnav-init.js')}}"></script>
	<script src="{{asset('js/demo.js')}}"></script>
	<script src="{{asset('vendor/moment/moment.min.js') }}"></script>
	<script src="{{asset('vendor/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
	<script src="{{asset('vendor/clockpicker/js/bootstrap-clockpicker.min.js') }}"></script>
	<script src="{{asset('vendor/jquery-asColor/jquery-asColor.min.js') }}"></script>
	<script src="{{asset('vendor/jquery-asGradient/jquery-asGradient.min.js') }}"></script>
	<script src="{{asset('vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js') }}"></script>
	<script src="{{asset('vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js') }}"></script>
	<script src="{{asset('vendor/pickadate/picker.js') }}"></script>
	<script src="{{asset('vendor/pickadate/picker.time.js') }}"></script>
	<script src="{{asset('vendor/pickadate/picker.date.js') }}"></script>
	<script src="{{asset('js/plugins-init/bs-daterange-picker-init.js') }}"></script>
	<script src="{{asset('js/plugins-init/clock-picker-init.js') }}"></script>
	<script src="{{asset('js/plugins-init/jquery-asColorPicker.init.js') }}"></script>
	<script src="{{asset('js/plugins-init/material-date-picker-init.js') }}"></script>
	<script src="{{asset('js/plugins-init/pickadate-init.js') }}"></script>
	<script src="{{ asset('vendor/jquery-smartwizard/dist/js/jquery.smartWizard.js') }}"></script>
	<script src="{{ asset('vendor/jquery-steps/build/jquery.steps.min.js') }}"></script>
    <script src="{{ asset('vendor/jquery-validation/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('js/plugins-init/jquery.validate-init.js') }}"></script>
    <script src="{{ asset('vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('js/plugins-init/datatables.init.js') }}"></script>
    <script src="{{ asset('vendor/datatables/js/jquery.dataTables.min.js') }}"></script>
	<script src="{{ asset('js/plugins-init/sparkline-init.js') }}"></script>
	<script src="{{ asset('vendor/jquery-sparkline/jquery.sparkline.min.js') }}"></script>
	<script src="{{ asset('js/plugins-init/widgets-script-init.js') }}"></script><script src="{{ asset('vendor/flot/jquery.flot.js') }}"></script>
    <script src="{{ asset('vendor/flot/jquery.flot.pie.js') }}"></script>
    <script src="{{ asset('vendor/flot/jquery.flot.resize.js') }}"></script>
    <script src="{{ asset('vendor/flot-spline/jquery.flot.spline.min.js') }}"></script>
	<script src="{{ asset('vendor/chartist/js/chartist.min.js') }}"></script>
    <script src="{{ asset('vendor/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js') }}"></script>

